### ISSUE TITLE
Advice on how to access images?

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#1]
Hi Lesley,

We're up and running with V0.1 of our Two Way Street app. Yeah! Here's a secret link for you:
http://twowaystreet.herokuapp.com/subjects/mammal

It looks like the data dumps don't have any references to image files in the RDF. I'm wondering if you have any advice or guidance for us on how to find images... we can't work out the connection between any of the object's IDs and the image URLs, if there are any.

I've been poking at Barry N via Twitter too, fyi.

g

**Comment by george08** [comment]
Just discovered there's a width param in the URL - cool!
http://www.britishmuseum.org/collectionimages/AN00012/AN00012839_001_l.jpg?width=500

**Comment by literarymachine** [comment]
I could not find this in the [sample datasets](https://github.com/goodformandspectacle/twowaystreet/tree/master/sample-datasets), but in the example I used in https://github.com/goodformandspectacle/twowaystreet/commit/90f30c087baefe2487b5b09df3952a2c7010c56c#commitcomment-10561353 ([this](http://collection.britishmuseum.org/id/object/EOC3130) object) the property used to link to images seems to be `http://erlangen-crm.org/current/P138i_has_representation`.

**Comment by lesleyauk** [comment]
Hi George,

This is looking cool already!

Unfortunately, there is zero relationship between asset IDs and object IDs.

How did you get your data dump? Image information is definitely in the RDF as 
"[has main representation]"(http://collection.britishmuseum.org/resource/bmo/PX_has_main_representation) and "[has representation]"(http://collection.britishmuseum.org/resource/ecrm/P138i_has_representation)

..
L

**Comment by lesleyauk** [comment]
It's also possible that your sample dataset happens to be entirely made up of objects that don't have any image. I noticed the dataset contains mainly prints and drawings, which are ironically perhaps the least likely object type to have images!

**Comment by george08** [comment]
Thanks, Lesley.

We're working with the August dump from here:
http://collection.britishmuseum.org/dumps/

@frankieroberto has worked out a way to get the images... We'll be doing an http request on demand. Those has_representation fields are missing from the RDF. (Looks like Label is too, at a glance.)

**Comment by literarymachine** [comment]
In [this dataset](http://collection.britishmuseum.org/dumps/satire-examples.zip) (see e.g. JCF13884.xml in there) the main representations are provided.

**Comment by george08** [comment]
Thanks @literarymachine - we're using the big dump... 

We've got 'em!
https://twowaystreet.herokuapp.com/things/JCF1749

**Comment by frankieroberto** [comment]
@george08 @literarymachine we're now getting the image url for `http://collection.britishmuseum.org/id/ontology/PX_has_main_representation` from the live British Museum Collections endpoint on demand on an object-by-object basis.

I couldn't see any of this data within the nquads data dumps though, which is a shame.

**Comment by literarymachine** [comment]
> I couldn't see any of this data within the nquads data dumps though, which is a shame.

A shame indeed, and it does make the data less open. Dumps should be complete. I would not be surprised if some weird copyright issue is the reason for that.
