### ISSUE TITLE
Make .json work

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#10]
E.g. https://twowaystreet.herokuapp.com/things/JCF1740.json

**Comment by george08** [comment]
Feel free to reassign

**Comment by infovore** [comment]
:+1:

**Comment by frankieroberto** [comment]
Live: https://twowaystreet.herokuapp.com/things/JCF286.json

Also there's a link from the bottom of https://twowaystreet.herokuapp.com/things/JCF286
