### ISSUE TITLE
Place a matching image in the background on facets list

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#18]
For a page like this: http://localhost:5000/facets/production_influenced_by, please find an image for each facet type, and place it in the background of the div (making sure it fills the space from centre outwards).

Be nice to choose a random one...

**Comment by george08** [comment]
(and on the home page now, too, please @infovore)

**Comment by infovore** [comment]
I think this is done - the pagination on /facets/acquisition_from , for instance, has made this possible. Can you confirm?

**Comment by george08** [comment]
Looks great!

(Just tell me how I can help in terms of flushing/populating caches.)
