### ISSUE TITLE
A gift for you

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#2]
Hi Steve,
Hope you're well. Thought you might like this:
https://twowaystreet.herokuapp.com/facets/uses_technique/woodblock
g

**Comment by siznax** [comment]
That's fantastic! Is it okay to share this?

**Comment by george08** [comment]
Tomorrow!

**Comment by george08** [comment]
It's live at twoway.st. You can tell trusted friends, but it's not finished yet.
