### ISSUE TITLE
Make row/column drawing on /facets/acquisition_from/* dynamic & responsive

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#21]
Now, we've set images on /facets/acquisition_from/* at 320px. They need to be set to 100% of their container instead.

Thinking we could, depending on viewport, ask for a different sized image. If we set img {width:100%} in CSS, we should be good.

Also need skeleton row/column for display to make everything responsive.

**Comment by infovore** [comment]
I think this is fixed and deployed - @george08, can you take a look and confirm?
