### ISSUE TITLE
Separate null fields in Thing page

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#7]
On a page like this: https://twowaystreet.herokuapp.com/things/JCF14577

You could create a new section at the bottom of the list to display all null fields. Give it an H4 - "Empty Fields" - and list the stuff like... 

'field name', 'field name', 'field name'

as in, please display them each in their own &lt;code&gt;&lt;/code&gt;

**Comment by george08** [comment]
Also, for any fields with values that can also take you to a list of other stuff, please make them into links.

(We can probably make that display more interesting than a table at some point too.)

**Comment by george08** [comment]
@frankieroberto let me know when you're ready to work on this. I bet we can make a better layout for not-null fields together very quickly.

**Comment by frankieroberto** [comment]
@george08 done this.
