### ISSUE TITLE
Created/Updated dates on Item page can be moved

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#8]
Always boring. Let's stick them at the bottom of the page, under everything else, in &lt;small&gt;
CREATED AT	2015-04-08T15:08:41+00:00
UPDATED AT	2015-04-08T16:00:05+00:00

**Comment by george08** [comment]
Related to #7

**Comment by infovore** [comment]
Just a note - these are added by my elasticsearch library, not actually in the dataset. I think the `#show` page should probably display a _filtered_ list of attributes rather than all of them.

**Comment by frankieroberto** [comment]
Removed these now
